
pipeline:
  deps:
    image: docker:git
    commands:    
     - git clone https://github.com/moengage/moe-truffleHog.git || true
  
  build:
    image: python:2.7.16-alpine
    commands:
      - pip list
      - cd moe-truffleHog
      - python truffleHog/truffleHog.py  --max_depth 1 --regex --branch master Alice-Test-App --entropy true > output.txt

