---
kind: pipeline
type: docker
name: Trufflehog

trigger:
  event:
    - pull_request
    
steps:
- name : Truffle-hog clone  
  image: docker:git
  commands:    
     - git clone https://github.com/moengage/moe-truffleHog.git
- name: Run truffle-hog
  image: python:3.5.1-alpine
  commands:
      - apk add --no-cache git
      - echo $DRONE_SOURCE_BRANCH
      - echo $DRONE_REPO
      - cd moe-truffleHog
      - git branch
      - git log
      -	pip install -r requirements.txt
      - python truffleHog/truffleHog.py  --max_depth 1 --regex --branch $DRONE_SOURCE_BRANCH "https://github.com/$DRONE_REPO.git" --entropy true > output.txt
      - cat output.txt
      - flag='False'
      - if [ -s output.txt ]; then flag='True'; fi
      - if [ "$flag" = 'True' ]; then echo "Tokens found" cat output.txt ;else echo "No Tokens Found"; fi
