
pipeline:
  clone:
    image: python:2.7.16-alpine
    commands:
     - git clone https://github.com/moengage/moe-truffleHog.git || true
  
  build:
    image: python:2.7.16-alpine
    commands:
      - pip list
      - cd moe-truffleHog

