clone:
  git:
    image: plugins/git:next
    commands:
      - pwd
      - sudo git clone https://github.com/moengage/moe-truffleHog.git
pipeline:
  build:
    image: python:3.5.1-alpine
    commands:
      - pwd
      - pip list
      - cd moe-truffleHog
      -	sudo pip install -r requirements.txt
      -	pip list
      -	sudo python setup.py install
      -	ls -la
      - sudo git status
      -	python truffleHog/truffleHog.py  --max_depth 1 --regex --branch master git@github.com:ParasJain-dev/Alice-Test-App.git --entropy true
