pipeline:
  deps:
    image: docker:git
    commands:    
     - git clone https://github.com/moengage/moe-truffleHog.git || true
  
  build:
    image: python:3.5.1-alpine
    commands:
      - pip list
      - cd moe-truffleHog
      -	pip install -r requirements.txt
      -	pip list
      -	python setup.py install
      -	ls -la
      - git status
      -	python truffleHog/truffleHog.py  --max_depth 1 --regex --branch master git@github.com:ParasJain-dev/Alice-Test-App.git --entropy true
