clone:
  git:
    image: plugins/git:next
    commands:
      - pwd
      - sudo git clone https://github.com/moengage/moe-truffleHog.git
  
pipeline:
  build:
    image: ubuntu
    commands:
      - yes | apt-get update
      - yes | apt-get upgrade
      - apt-get install python-pip
      - pwd
      - pip list
      - cd moe-truffleHog
      -	pip install -r requirements.txt
      -	pip list
      -	python setup.py install
      -	ls -la
      -	python truffleHog/truffleHog.py  --max_depth 1 --regex --branch master git@github.com:ParasJain-dev/Alice-Test-App.git --entropy true
