---

kind: pipeline
type: docker
name: Git secret

steps:
- name: clone trufflehog
  image: docker:git
  commands:
    - git clone https://github.com/moengage/moe-truffleHog.git
  when:
    event:
    - pull_request

- name: run trufflehog
  image: python:3.5.1-alpine
  commands:
    - apk add --no-cache git
    - branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
    - echo $branch
    - cd moe-truffleHog
    -	pip install -r requirements.txt
    -	python truffleHog/truffleHog.py  --max_depth 1 --regex --branch test2 https://github.com/ParasJain-dev/Alice-Test-App.git --entropy true

  when:
    event:
    - pull_request

